[project]
name = "flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "lightgbm>=4.6.0",
    "mlflow==3.9.0",
    "pytest>=9.0.2",
    "seaborn>=0.13.2",
    "xgboost>=3.1.3",
]
